#!/usr/bin/env python

import os
import glob

CacheDir(os.environ.get("SCONS_CACHE", ".scons_cache/"))

env = SConscript("godot-cpp/SConstruct")

if env["platform"] == "windows":
    env.Append(CPPPATH=["vendor/webview/include", "vendor/webview2/include"])
    env.Append(LIBS=["advapi32", "comdlg32", "ole32", "shell32", "shlwapi", "user32", "version"])
elif env["platform"] == "macos":
    env.Append(CXXFLAGS=["-fblocks"])
    env.Append(LINKFLAGS=["-framework", "Cocoa", "-framework", "WebKit"])
    env.Append(LIBS=["dl"])
elif env["platform"] == "linux":
    env.Append(LIBS=["dl"])

# Auto-discover include directories
for root, dirs, files in os.walk("include"):
    env.Append(CPPPATH=[root])

# Keep build files inside this project
build_dir = "build"
env.VariantDir(build_dir, "src", duplicate=0)

# Discover sources
sources = glob.glob("src/**/*.cpp", recursive=True)
sources += glob.glob("src/**/*.c", recursive=True)
if env["platform"] == "macos":
    sources += glob.glob("src/**/*.mm", recursive=True)

build_sources = [s.replace("src", build_dir, 1) for s in sources]

# Output binary to the installable Godot addon payload.
out_dir = "../godot/addons/fennara/bin"

if env["platform"] == "macos":
    file_name = "libfennara.{}.{}".format(env["platform"], env["target"])
    library = env.SharedLibrary(
        "{}/{}.framework/{}".format(out_dir, file_name, file_name),
        source=build_sources,
    )
else:
    library = env.SharedLibrary(
        "{}/libfennara{}{}".format(out_dir, env["suffix"], env["SHLIBSUFFIX"]),
        source=build_sources,
    )

targets = [library]

if env["platform"] == "linux":
    helper_env = env.Clone()
    helper_env.Append(CPPPATH=["vendor/webview/include"])
    helper_env.Append(CXXFLAGS=["-fexceptions"])
    helper_env.ParseConfig("pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.1")
    helper = helper_env.Program(
        "{}/fennara-chat-webview".format(out_dir),
        source=["helpers/linux_chat_webview.cpp"],
    )
    targets.append(helper)

Default(targets)
